#!/usr/bin/env python3
"""commit_scope.py — decide which paths a session may stage (PH16-T22 rule D).

`commit-all` ran `git add -A`, so every change present in the tree entered this
session's commit: a concurrent writer's edits, and work a previous session left
behind. The commit then claimed authorship of changes nobody in this session made,
and the self-review record — bound to a content hash of *this* diff — covered
files its reviewer never saw. Found live 2026-08-13 (b), when an `@life` session
wrote a fix into this tree while it was being closed.

Rule (B) gave the workspace a per-session identity stamped `acquired_at`. That is
what makes "the paths its session touched" answerable at all, and this module is
the answer: a working-tree change is in scope when it was modified at or after
the session took the lock.

**Direction of failure, chosen deliberately.** Anything unattributable — a
deletion (no mtime to read), an unreadable stat, a malformed stamp — is REPORTED
and LEFT OUT rather than swept in. A path missing from a commit is visible in the
next `git status`; a wrongly attributed one is invisible forever. `--all` is the
one way back to blanket staging, and it says so in the output.

PH16-T36 — leaving a path out is not the same as stopping the commit. `f4e7463`
names PH16-T34 and PH16-T35 across 33 lines and contains one file: an inbox note
another workspace wrote here. Attribution had produced the empty set (a session
resumed after a rate limit took the lock *after* writing its work, so the journal
covered nothing and the mtime rule excluded all 22 of its own paths), this module
printed `staged 0 path(s) · 22 left for their author`, and `commit-all` committed
anyway — because its emptiness test was `git diff --cached --quiet`, and the index
still held one path staged during the earlier tenure. The guard against an empty
commit passed *because of* the very leftover that made the commit wrong.

So the module now owns the verdict, not just the plan:

    0  proceed — the commit will contain exactly what this run attributed
    2  the scope could not be computed at all (unchanged)
    3  REFUSED — the index holds a path this run did not attribute
    4  nothing attributable — there is no commit to make, and that is not an error

Deliberately nothing here reads the commit *message*. The obvious rule — every
task id in the message must have its plan or its named test staged — was replayed
against the last 40 commits before it was written and refuses 14 of 29 correct
ones: a closure commit legitimately stages handover and memory files and no test.
A guard that fires on half of all good commits teaches the reflex that let this
one through.
"""

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


class ScopeError(RuntimeError):
    """The scope could not be computed. Never degrade to `git add -A`."""


# Artefacts a `just` recipe generates, not a tool call — so they never appear in
# the write journal however faithfully it records. Dropping them would quietly
# remove `verify-safe`'s own output, the codemap and the changelog from every
# commit: a fix that breaks the thing it was protecting.
#
# `gate_check.BOOKKEEPING` already enumerates this class for the leash, and is
# reused rather than re-listed. `.ai/codemap.md` is added *here only*: it is
# regenerated by `just codemap` during closure, but widening the leash's
# allowlist is a different question with a different threat model, and is
# deliberately not answered as a side effect of this one.
GENERATED_EXTRA = (".ai/codemap.md",)


def _generated() -> tuple:
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        import gate_check
        return tuple(gate_check.BOOKKEEPING) + GENERATED_EXTRA
    except Exception:  # noqa: BLE001
        return GENERATED_EXTRA


@dataclass
class Plan:
    staged: list = field(default_factory=list)
    skipped: dict = field(default_factory=dict)
    everything: bool = False
    #: paths git reported as already staged when the plan was computed — read from
    #: the same snapshot as `staged`/`skipped`, never from a later `git diff --cached`.
    in_index: list = field(default_factory=list)
    # "journal" — authorship was read from the write journal.
    # "mtime"   — no journal covers this tenure, so the old rule ran instead.
    # An operator must never have to guess which of the two produced a commit.
    attribution: str = "mtime"


def now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _parse(stamp: str) -> float:
    if not isinstance(stamp, str) or not stamp.strip():
        raise ScopeError("no session start stamp — cannot attribute any change")
    try:
        text = stamp.strip().replace("Z", "+00:00")
        dt = datetime.fromisoformat(text)
    except ValueError as exc:
        raise ScopeError(f"unreadable session start stamp {stamp!r}: {exc}") from exc
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.timestamp()


def _candidates(root: Path):
    """(path, deleted, in_index) for every change git itself reports. `-z` because
    a repo with a space in a filename must not silently drop it.

    `in_index` is the first status column: anything other than a space or `?` means
    the path is already staged. It is read from *this* snapshot rather than by a
    separate `git diff --cached` call, and `plan()` carries it out on the Plan, so
    "what is in the index" and "what changed" can never come from two different
    views of a tree an agent is still writing to.
    """
    run = subprocess.run(["git", "status", "--porcelain=1", "-z", "--untracked-files=all"],
                         cwd=root, capture_output=True, text=True)
    if run.returncode != 0:
        raise ScopeError(f"git status failed: {run.stderr.strip()}")
    out, records = [], [r for r in run.stdout.split("\0") if r]
    i = 0
    while i < len(records):
        rec = records[i]
        code, path = rec[:2], rec[3:]
        if code[0] == "R":
            # a rename's record is followed by its source path
            i += 1
            if i < len(records):
                # A rename is only ever detected in the index, so its source path
                # is staged by construction — derived from the same column as every
                # other record rather than asserted separately.
                out.append((records[i], True, code[0] not in (" ", "?")))
        out.append((path, "D" in code, code[0] not in (" ", "?")))
        i += 1
    return out


def plan(root: Path, since: str, everything: bool = False,
         authored: set | None = None, contested: dict | None = None) -> Plan:
    """`authored` is the set of repo-relative paths this tenure provably wrote
    (PH16-T24), or **None** when no journal covers this tenure.

    None is not the empty set. None means "nobody recorded the authors", and the
    mtime rule runs alone — which is the honest answer for the 46 workspaces the
    hook has not reached and for every session before it existed. `set()` means
    "the journal ran and this session wrote none of these", which is a verdict.
    """
    root = Path(root)
    candidates = _candidates(root)
    in_index = sorted(rel for rel, _, staged in candidates if staged)
    if everything:
        return Plan(staged=[p for p, _, _ in candidates], skipped={}, everything=True,
                    attribution="all", in_index=in_index)

    cutoff = _parse(since)
    generated = _generated()
    result = Plan(attribution="journal" if authored is not None else "mtime",
                  in_index=in_index)
    for rel, deleted, _staged in candidates:
        if deleted:
            result.skipped[rel] = (
                "deleted — a removed file has no modification time, so it cannot "
                "be attributed to this session (stage it yourself, or use --all)")
            continue
        # PH16-T38 — the journal is consulted BEFORE the clock, because it answers
        # the question the clock only approximates. An entry names the session that
        # wrote the path; `acquired_at` merely bounds a window that routinely opens
        # *after* the work (`session-start` swallows a failed lock acquisition, so
        # the lock is often first taken at credit time). Checking mtime first meant
        # a path this session provably wrote was thrown out for being "too old" —
        # and which ones survived depended on whether a pre-commit fixer happened
        # to rewrite them, which is how HEAD 28e5b0e came to fail its own suite.
        if authored is not None and rel in authored:
            result.staged.append(rel)
            continue
        if contested and rel in contested:
            # This session did write it — and lost it. Reported specifically,
            # because the generic "this session never wrote it" reason would be
            # false here, and a false reason sends the operator to `--all`.
            mine_at, theirs_at = contested[rel]
            result.skipped[rel] = (
                f"this session wrote it at {mine_at:%Y-%m-%d %H:%M}Z, but another session "
                f"wrote it again at {theirs_at:%Y-%m-%d %H:%M}Z — the contents on disk are "
                f"theirs, and committing them here would put their work under this "
                f"session's review hash (stage it yourself if you are certain, or use --all)")
            continue
        try:
            mtime = (root / rel).stat().st_mtime
        except OSError as exc:
            result.skipped[rel] = f"could not stat the file ({exc.strerror}) — not attributable"
            continue
        if mtime + 1e-6 < cutoff:
            result.skipped[rel] = (
                "modified before this session took the workspace lock — it belongs "
                "to whoever made it, not to this commit")
            continue
        # Inside the window, and the journal did not claim it. mtime has now said
        # everything it can say: it proves the file changed *during* this session
        # and cannot prove it changed *by* it. Only the journal can answer that,
        # and only when it covers this tenure at all.
        if authored is not None and not rel.startswith(generated):
            result.skipped[rel] = (
                "changed during this session, but this session never wrote it — "
                "another writer is in this tree, or it was edited outside the "
                "harness (stage it yourself, or use --all)")
            continue
        result.staged.append(rel)
    result.staged.sort()
    return result


def apply(root: Path, plan_: Plan) -> None:
    if not plan_.staged:
        return
    subprocess.run(["git", "add", "--", *plan_.staged], cwd=root, check=True)


def unattributed(plan_: Plan) -> list:
    """Paths already staged that this run did not attribute to this session.

    The set is computed **before** anything is added, so a refusal leaves the index
    exactly as the operator last saw it — a half-staged tree is a scope no commit
    message describes, which is the state this whole module exists to prevent.
    """
    mine = set(plan_.staged)
    return [rel for rel in plan_.in_index if rel not in mine]


def report_leftovers(leftovers: list) -> None:
    # The refusal is the conclusion of everything printed above it, and stdout and
    # stderr are buffered independently — unflushed, a piped log shows the verdict
    # before the evidence it was drawn from.
    sys.stdout.flush()
    print(f"🛑 commit scope refused — the index holds {len(leftovers)} path(s) this run did "
          f"not attribute to this session:", file=sys.stderr)
    for rel in leftovers:
        print(f"     • {rel}", file=sys.stderr)
    print("   Staged, but not staged by this run: each entered the index earlier — another\n"
          "   tenure of this session, or a hand `git add` — so committing now would carry it\n"
          "   under a message written about different work. That is how commit f4e7463 came\n"
          "   to name two tasks and contain neither.\n"
          "   Two ways forward, both deliberate:\n"
          "     git restore --staged <path>       drop it, then run this again\n"
          "     just commit-all \"<msg>\" --all     take it knowingly, with everything else",
          file=sys.stderr)


def session_started_at(root: Path) -> str:
    """`acquired_at` from the rule-(B) session lock — the only stamp that means
    'this session', as opposed to 'this process', started."""
    try:
        lock = json.loads((Path(root) / ".ai" / "session-lock.json").read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ScopeError(
            "no .ai/session-lock.json — this session never took the workspace lock, "
            "so nothing can be attributed to it. Run `just session-start`.")
    except Exception as exc:
        raise ScopeError(f"session lock unreadable: {exc}") from exc
    return str(lock.get("acquired_at") or "")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Stage only what this session touched.")
    ap.add_argument("--root", default=None)
    ap.add_argument("--since", default=None,
                    help="ISO stamp; defaults to the session lock's acquired_at")
    ap.add_argument("--all", dest="everything", action="store_true",
                    help="stage every change in the tree (the pre-PH16-T22 behaviour)")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--allow-partial", action="store_true",
                    help="accept a commit that leaves changed paths behind (exit 0 "
                         "instead of 5). The escape hatch, not the default.")
    args = ap.parse_args(argv)

    root = Path(args.root) if args.root else Path(
        subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True,
                       text=True).stdout.strip() or os.getcwd())
    try:
        since = args.since or ("" if args.everything else session_started_at(root))
        authored, contested = None, None
        if not args.everything:
            try:
                sys.path.insert(0, str(Path(__file__).resolve().parent))
                import write_journal
                tenure = write_journal.tenure_sessions(root)
                authored = write_journal.paths_for(root, tenure, since)
                contested = write_journal.contested(root, tenure)
            except Exception:  # noqa: BLE001
                # A broken journal is no evidence, which is the fallback — never
                # a refusal, and never a silent claim that nothing was authored.
                authored, contested = None, None
        p = plan(root, since, everything=args.everything, authored=authored,
                 contested=contested)
    except ScopeError as exc:
        print(f"🛑 commit scope refused — {exc}", file=sys.stderr)
        print("   Not falling back to `git add -A`: that is the bug this replaces.",
              file=sys.stderr)
        return 2

    if p.everything:
        print(f"⚠️  --all: staging every change in the tree ({len(p.staged)} path(s)), "
              f"including any this session did not make.")
    elif p.attribution == "mtime":
        # Named every time, deliberately. A silent fallback would present a
        # timestamp as authorship evidence, which is the defect this replaces.
        print("ℹ️  No write journal covers this session, so authorship falls back to "
              "modification time.\n"
              "   That proves a file changed DURING this session, not that this session "
              "wrote it.")
    for rel, why in sorted(p.skipped.items()):
        print(f"  ⏭️  not staged: {rel}\n       {why}")

    leftovers = unattributed(p)
    verb = "staged" if args.apply else "would stage"
    if leftovers:
        # Reported before `git add`, so the refusal changes nothing. No ✅ here: a
        # tick on the line above a refusal is the shape that got read as success.
        print(f"  ⛔ nothing {verb} — refusing before touching the index "
              f"({len(p.staged)} path(s) were attributable to this session)")
        report_leftovers(leftovers)
        return 3

    if args.apply:
        apply(root, p)
    print(f"  ✅ {verb} {len(p.staged)} path(s) attributable to this session"
          + (f" · {len(p.skipped)} left for their author" if p.skipped else ""))
    if not p.staged:
        # The index is empty too — `leftovers` would have caught anything in it — so
        # there is genuinely nothing to commit. Said here rather than inferred by the
        # caller from `git diff --cached`, which is the substitution that shipped
        # f4e7463.
        print("  ⏭️  nothing attributable to this session — no commit made.")
        return 4
    # An operator could not see this commit's contents before making it: the last
    # line before `git commit` was a count, and the count was 0.
    print(f"  📦 this commit will contain {len(p.staged)} path(s):")
    for rel in p.staged:
        print(f"       • {rel}")
    report_exclusions(p)
    # PH23-T02 / Q2. Exit 5 = "staged, and it is a PARTIAL commit."
    #
    # `report_exclusions` was the previous answer and it was not enough — it is
    # printing, and printing is walked past. The worst recorded instance shipped
    # `scripts/session_budget.py` without `tests/test_session_budget.py` and
    # without the `.ai/os_version.json` bump the commit existed to release, so
    # HEAD failed its own suite; the exclusions block was on screen the whole
    # time. Three incidents, all with the warning visible.
    #
    # The index keeps what was staged, so this is a stop and never a loss: stage
    # the rest, or re-run with `--all`, or pass `--allow-partial` when the
    # exclusion really is deliberate. What is no longer possible is committing
    # part of a coherent change without saying you meant to.
    # PH24-T12 (d). Checked BEFORE the partial rule, and with its own exit code:
    # "this commit is partial" is settled by `--allow-partial`, and this one never
    # is, so collapsing them would offer a cure that makes the problem worse.
    announced = announced_but_absent(p, root)
    if announced:
        report_announced(announced)
        return EXIT_ANNOUNCED
    if p.skipped and not args.allow_partial:
        print("  ⛔ PARTIAL COMMIT — refusing. The paths above are staged and stay "
              "staged;\n     nothing is lost. Stage the rest, or re-run with --all, "
              "or pass\n     --allow-partial if leaving them out is deliberate.")
        return 5
    return 0


# The two halves of the interlock below (PH24-T12). Narrow on purpose: this is
# not "is this commit coherent?", which is undecidable — it is the one shape that
# has actually shipped broken, twice.
CODE_DIRS = ("scripts/", "tests/")
DOC_SUFFIXES = (".md", ".rst", ".txt")
EXIT_ANNOUNCED = 6


def announced_but_absent(plan_: Plan, root: Path) -> list:
    """Staged docs that name excluded code. `[(doc, code), …]` (PH24-T12).

    The catastrophe `--allow-partial` was pointed at on 2026-08-17. A session
    that inherits an unshipped tree attributes **nothing** — `write_journal` is
    per-session — so all 28 files the previous session wrote were excluded,
    including `scripts/run_tests.py`. The pipeline's one reachable escape hatch
    would then have committed `AI_CHANGELOG.md`, `tasks.md` and
    `activeContext.md`, all three describing that delivery, without it.

    That is `28e5b0e`'s shape: a commit whose docs announce code it does not
    contain, HEAD failing its own suite. `report_exclusions()` printed the
    warning through all three incidents, which is exactly why this refuses
    instead of printing a fourth time.

    Both sides are deliberately narrow. Code means a `.py` under `scripts/` or
    `tests/` — the files whose absence breaks the tree — not any excluded path.
    A doc counts only if its **text** names the path or its basename, so a
    partial commit that merely happens to include a `.md` is untouched; refusing
    those would make the escape hatch useless and this message untrue.

    Accepted blind spot, stated where it fires: a doc that describes the code
    without naming it passes. The full-suite gate remains the backstop.
    """
    absent = sorted(rel for rel in plan_.skipped
                    if rel.endswith(".py") and rel.startswith(CODE_DIRS))
    if not absent:
        return []
    pairs = []
    for doc in plan_.staged:
        if not doc.endswith(DOC_SUFFIXES):
            continue
        try:
            text = (Path(root) / doc).read_text(encoding="utf-8", errors="replace")
        except OSError:
            # Unreadable is not evidence of a claim. The mtime rule's direction
            # applies here too: never invent a refusal from a file we cannot read.
            continue
        for code in absent:
            if code in text or Path(code).name in text:
                pairs.append((doc, code))
    return pairs


def report_announced(pairs: list) -> None:
    sys.stdout.flush()
    print(f"🛑 refusing — {len(pairs)} staged document(s) announce code this commit "
          f"does NOT contain:", file=sys.stderr)
    for doc, code in pairs:
        print(f"     • {doc}  names  {code}   ← left out of this commit", file=sys.stderr)
    print("   This is the shape of commit 28e5b0e: docs and a changelog describing a\n"
          "   delivery, without the delivery, so HEAD fails its own test suite. It is\n"
          "   why `--allow-partial` does not cover this case — it is the case.\n"
          "   The way out is to include the code:\n"
          "     git add -- <the paths above>            then run this again\n"
          "     just ship \"<msg>\" --all                take the whole tree, knowingly\n"
          "   Narrow by design: this catches a doc that NAMES an excluded\n"
          "   scripts/|tests/ .py file. A doc describing it without naming it passes.",
          file=sys.stderr)


def report_exclusions(plan_: Plan) -> None:
    """Name what is being LEFT BEHIND, last (PH16-T38).

    The skipped paths were already printed — above the contents, above the tick,
    and above whatever `git commit` prints next. That is reporting, and it was
    not enough: `commit-all` staged 22 of 28 paths on 2026-08-15, said nothing an
    operator read as a warning, and the resulting HEAD failed its own suite. The
    exclusions are repeated here as the final block, because the last thing
    printed is the thing that is read, and because a commit that omits part of a
    coherent change is only recoverable while somebody still knows it happened.
    """
    if not plan_.skipped:
        return
    print(f"  ⚠️  NOT in this commit — {len(plan_.skipped)} changed path(s) left behind:")
    for rel in sorted(plan_.skipped):
        print(f"       ✗ {rel}")
    print("     Each is a real change in your tree that this commit does not contain.\n"
          "     If any of them belongs with the work above, this commit is a partial\n"
          "     one: stage them yourself, or re-run with --all, before pushing.")


if __name__ == "__main__":
    raise SystemExit(main())
